### ISSUE TITLE
Issue with libsuperlu.4.3.dylib" on Mac os

### ISSUE THREAD

**Issue by rinauoy** [OPM/opm-core#925] opened 2015-11-11 04:20 UTC
Dear All,

I have managed to build the opm-core from source. However, when I tried to run 'flow', I have the following error: 
```
Rinas-MacBook-Pro:~ rinabuoy$ /Users/rinabuoy/opm-autodiff-build/bin/flow ; exit;
dyld: Library not loaded: /usr/local/opt/superlu/lib/libsuperlu.4.3.dylib"
  Referenced from: /Users/rinabuoy/opm-autodiff-build/bin/flow
  Reason: image not found
Trace/BPT trap: 5
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

It appeared this issue was reported before.

Thanks very much, 

Rina

**Comment by atgeirr** [comment] 2015-11-11 07:51
Yes I have seen this issue before, and cannot reproduce it on a new system. I never found out exactly what happened, but I think a workaround would be
```
cp /usr/local/opt/superlu/lib/libsuperlu.4.3.dylib /usr/local/opt/superlu/lib/libsuperlu.4.3.dylib\"
```
The problem is that some string manipulation in the build system goes wrong (possibly due to some BSD/Mac OS vs. Linux differences in tools like sed), resulting in an extra `"` in the lib name. The above command duplicates the lib to the name expected (which includes the `"`).

**Comment by atgeirr** [comment] 2016-04-13 12:24
Since there were no further comments, and we were not able to reproduce the issue on recent versions of the platform I'll close this. Feel free to reopen if new information arises, or the problem comes back.

**Closed by atgeirr** 2016-04-13 12:24 UTC

**Comment by dhan16** [comment] 2017-08-13 07:35
hmm. encountered the same issue today and worked around with the cp
